<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LogME.proto

namespace Logme;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>logme.AddLogRequest</code>
 */
class AddLogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string content = 1;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>string date = 2;</code>
     */
    protected $date = '';
    /**
     * Generated from protobuf field <code>string level = 3;</code>
     */
    protected $level = '';
    /**
     * Generated from protobuf field <code>.logme.LogType type = 4;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $content
     *     @type string $date
     *     @type string $level
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LogME::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date = 2;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Generated from protobuf field <code>string date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string level = 3;</code>
     * @return string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>string level = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.logme.LogType type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.logme.LogType type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Logme\LogType::class);
        $this->type = $var;

        return $this;
    }

}

